server:
  port: 8080
spring:
  application:
    name: "storeCarGradle"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://stevenrua:stevenrua9210@cluster0.pfmkpjo.mongodb.net/Events?retryWrites=true&w=majority"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
